/obj/machinery/vending/autodrobe
	name = "\improper AutoDrobe"
	desc = "A vending machine for costumes."
	icon_state = "theater"
	icon_deny = "theater-deny"
	panel_type = "panel16"
	product_slogans = "Dress for success!;Suited and booted!;It's show time!;Why leave style up to fate? Use AutoDrobe!"
	vend_reply = "Thank you for using AutoDrobe!"
	product_categories = list(
		list(
			"name" = "Costumes",
			"icon" = "mask",
			"products" = list(
				/obj/item/clothing/under/costume/gladiator = 3,
				/obj/item/clothing/head/helmet/gladiator = 3,
				/obj/item/clothing/suit/toggle/labcoat/mad = 3,
				/obj/item/clothing/suit/bio_suit/plaguedoctorsuit = 3,
				/obj/item/clothing/head/bio_hood/plague = 3,
				/obj/item/clothing/mask/gas/plaguedoctor = 3,
				/obj/item/clothing/under/rank/medical/doctor/nurse = 3,
				/obj/item/clothing/suit/toggle/owlwings = 3,
				/obj/item/clothing/under/costume/owl = 3,
				/obj/item/clothing/mask/gas/owl_mask = 3,
				/obj/item/clothing/suit/toggle/owlwings/griffinwings = 3,
				/obj/item/clothing/under/costume/griffin = 3,
				/obj/item/clothing/shoes/griffin = 3,
				/obj/item/clothing/head/costume/griffin = 3,
				/obj/item/clothing/under/costume/pirate = 3,
				/obj/item/clothing/suit/costume/pirate = 3,
				/obj/item/clothing/head/costume/pirate = 3,
				/obj/item/clothing/head/costume/pirate/bandana = 3,
				/obj/item/clothing/shoes/pirate = 3,
				/obj/item/clothing/under/costume/soviet = 3,
				/obj/item/clothing/head/costume/ushanka = 3,
				/obj/item/clothing/accessory/vest_sheriff = 3,
				/obj/item/clothing/head/cowboy/brown = 3,
				/obj/item/clothing/head/cowboy/red = 3,
				/obj/item/clothing/head/cowboy/black = 3,
				/obj/item/clothing/head/costume/sombrero/green = 3,
				/obj/item/clothing/suit/costume/poncho = 3,
				/obj/item/clothing/suit/costume/poncho/green = 3,
				/obj/item/clothing/suit/costume/poncho/red = 3,
				/obj/item/clothing/suit/costume/snowman = 3,
				/obj/item/clothing/head/costume/snowman = 3,
				/obj/item/clothing/under/costume/referee = 3,
				/obj/item/clothing/mask/whistle = 3,
				/obj/item/storage/backpack/henchmen = 5,
				/obj/item/clothing/under/costume/henchmen = 5,
				/obj/item/clothing/head/costume/jackbros = 5,
				/obj/item/clothing/under/costume/jackbros = 5,
				/obj/item/clothing/under/costume/deckers = 5,
				/obj/item/clothing/under/costume/sailor = 3,
				/obj/item/clothing/head/costume/delinquent = 3,
				/obj/item/clothing/suit/costume/dracula = 3,
				/obj/item/clothing/under/costume/draculass = 3,
				/obj/item/clothing/suit/costume/gothcoat = 3,
				/obj/item/clothing/glasses/eyepatch = 3,
				/obj/item/clothing/glasses/eyepatch/medical = 3,
				/obj/item/clothing/under/costume/gi = 4,
				/obj/item/clothing/head/soft/propeller_hat = 3,
				/obj/item/clothing/neck/bowtie/rainbow = 3,
			),
		),
		list(
			"name" = "Supernatural",
			"icon" = "hand-sparkles",
			"products" = list(
				/obj/item/clothing/suit/costume/imperium_monk = 3,
				/obj/item/clothing/suit/chaplainsuit/holidaypriest = 3,
				/obj/item/clothing/suit/chaplainsuit/habit = 3,
				/obj/item/clothing/head/chaplain/habit_veil = 3,
				/obj/item/clothing/suit/chaplainsuit/whiterobe = 3,
				/obj/item/clothing/head/wizard/marisa/fake = 3,
				/obj/item/clothing/suit/wizrobe/marisa/fake = 3,
				/obj/item/clothing/head/costume/witchwig = 3,
				/obj/item/staff/broom = 3,
				/obj/item/clothing/suit/wizrobe/fake = 3,
				/obj/item/clothing/head/wizard/fake = 3,
				/obj/item/staff = 3,
				/obj/item/clothing/head/costume/shrine_wig = 3,
				/obj/item/clothing/suit/costume/shrine_maiden = 3,
				/obj/item/gohei = 3,
			),
		),
		list(
			"name" = "Entertainers",
			"icon" = "masks-theater",
			"products" = list(
				/obj/item/clothing/under/rank/civilian/clown/blue = 3,
				/obj/item/clothing/under/rank/civilian/clown/green = 3,
				/obj/item/clothing/under/rank/civilian/clown/yellow = 3,
				/obj/item/clothing/under/rank/civilian/clown/orange = 3,
				/obj/item/clothing/under/rank/civilian/clown/purple = 3,
				/obj/item/clothing/mask/gas/sexyclown = 3,
				/obj/item/clothing/under/rank/civilian/clown/sexy = 3,
				/obj/item/clothing/head/beret = 6,
				/obj/item/clothing/mask/gas/sexymime = 3,
				/obj/item/clothing/under/rank/civilian/mime/sexy = 3,
				/obj/item/clothing/under/rank/civilian/mime/skirt = 3,
				/obj/item/clothing/under/rank/civilian/clown/jester = 3,
				/obj/item/clothing/head/costume/jester = 3,
				/obj/item/clothing/shoes/jester_shoes = 3,
				/obj/item/clothing/under/costume/villain = 3,
				/obj/item/clothing/suit/costume/joker = 3,
				/obj/item/clothing/under/costume/joker = 3,
				/obj/item/clothing/shoes/singery = 3,
				/obj/item/clothing/under/costume/singer/yellow = 3,
				/obj/item/clothing/shoes/singerb = 3,
				/obj/item/clothing/under/costume/singer/blue = 3,
				/obj/item/clothing/head/costume/cueball = 3,
			),
		),
		list(
			"name" = "Fancy",
			"icon" = "user-tie",
			"products" = list(
				/obj/item/clothing/under/rank/captain/suit = 3,
				/obj/item/clothing/under/rank/captain/suit/skirt = 3,
				/obj/item/clothing/under/costume/schoolgirl = 3,
				/obj/item/clothing/under/costume/schoolgirl/red = 3,
				/obj/item/clothing/under/costume/schoolgirl/green = 3,
				/obj/item/clothing/under/costume/schoolgirl/orange = 3,
				/obj/item/clothing/under/dress/skirt = 3,
				/obj/item/clothing/neck/tie = 3,
				/obj/item/clothing/head/hats/tophat = 3,
				/obj/item/clothing/under/costume/kilt = 3,
				/obj/item/clothing/glasses/monocle =1,
				/obj/item/clothing/head/hats/bowler = 3,
				/obj/item/cane = 3,
				/obj/item/clothing/under/dress/sundress = 3,
				/obj/item/clothing/suit/costume/whitedress = 3,
				/obj/item/clothing/suit/costume/changshan_red = 3,
				/obj/item/clothing/suit/costume/changshan_blue = 3,
				/obj/item/clothing/suit/costume/cheongsam_red = 3,
				/obj/item/clothing/suit/costume/cheongsam_blue = 3,
			),
		),
		list(
			"name" = "Animals",
			"icon" = "paw",
			"products" = list(
				/obj/item/clothing/head/costume/kitty = 3,
				/obj/item/clothing/head/costume/rabbitears =1,
				/obj/item/clothing/suit/costume/chickensuit = 3,
				/obj/item/clothing/head/costume/chicken = 3,
				/obj/item/clothing/suit/hooded/carp_costume = 3,
				/obj/item/clothing/suit/hooded/ian_costume = 3,
				/obj/item/clothing/suit/hooded/bee_costume = 3,
				/obj/item/clothing/mask/animal/small/bat = 3,
				/obj/item/clothing/mask/animal/small/bee = 3,
				/obj/item/clothing/mask/animal/small/bear = 3,
				/obj/item/clothing/mask/animal/small/raven = 3,
				/obj/item/clothing/mask/animal/small/jackal = 3,
				/obj/item/clothing/mask/animal/small/fox = 3,
				/obj/item/clothing/mask/animal/frog = 3,
				/obj/item/clothing/mask/animal/small/rat = 3,
				/obj/item/clothing/mask/animal/pig = 3,
				/obj/item/clothing/mask/animal/cowmask = 3,
				/obj/item/clothing/mask/animal/horsehead = 3,
			),
		),
		list(
			"name" = "Service",
			"icon" = "kitchen-set",
			"products" = list(
				/obj/item/clothing/under/costume/buttondown/slacks/service = 3,
				/obj/item/clothing/under/costume/buttondown/skirt/service = 3,
				/obj/item/clothing/neck/bowtie = 6,
				/obj/item/clothing/accessory/waistcoat = 3,
				/obj/item/clothing/under/suit/waiter = 3,
				/obj/item/clothing/suit/apron = 3,
				/obj/item/clothing/suit/apron/overalls = 3,
				/obj/item/clothing/head/costume/maidheadband = 3,
				/obj/item/clothing/under/costume/maid = 3,
				/obj/item/clothing/gloves/maid = 3,
				/obj/item/clothing/neck/maid = 3,
				/obj/item/clothing/under/rank/civilian/janitor/maid = 3,
				/obj/item/clothing/accessory/maidapron = 3,
			),
		),
		list(
			"name" = "Other",
			"icon" = "star",
			"products" = list(
				/obj/item/clothing/head/wig/random = 6,
				/obj/item/clothing/head/flatcap = 3,
				/obj/item/clothing/suit/jacket/miljacket = 3,
				/obj/item/clothing/shoes/workboots/black = 6, // NON-MODULE CHANGE
				/obj/item/clothing/mask/fakemoustache = 3,
				/obj/item/clothing/glasses/cold = 3,
				/obj/item/clothing/glasses/heat = 3,
				/obj/item/clothing/mask/gas/cyborg = 3,
				/obj/item/clothing/mask/joy = 3,
				/obj/item/clothing/mask/gas/prop = 6,
				/obj/item/clothing/mask/gas/atmosprop = 3,
				/obj/item/clothing/mask/animal/small/tribal = 3,
			),
		),
	)

	contraband = list(
		/obj/item/clothing/glasses/blindfold = 3,
		/obj/item/clothing/glasses/sunglasses/gar = 2,
		/obj/item/clothing/head/costume/lobsterhat = 3,
		/obj/item/clothing/head/costume/powdered_wig = 3,
		/obj/item/clothing/head/costume/tv_head = 3,
		/obj/item/clothing/mask/muzzle = 2,
		/obj/item/clothing/shoes/clown_shoes/meown_shoes = 3,
		/obj/item/clothing/shoes/clown_shoes/moffers = 3,
		/obj/item/clothing/shoes/ducky_shoes = 3,
		/obj/item/clothing/shoes/jackboots = 3, // NON-MODULE CHANGE
		/obj/item/clothing/suit/costume/judgerobe = 3,
		/obj/item/clothing/under/costume/lobster = 3,
		/obj/item/gun/magic/wand/nothing = 2,
		/obj/item/skillchip/musical = 3,
		/obj/item/storage/box/tape_wizard = 3,

	)
	premium = list(
		/obj/item/clothing/suit/costume/pirate/captain = 6,
		/obj/item/clothing/under/rank/civilian/clown/rainbow = 3,
		/obj/item/clothing/head/helmet/roman/fake = 3,
		/obj/item/clothing/head/helmet/roman/legionnaire/fake = 3,
		/obj/item/clothing/under/costume/roman = 3,
		/obj/item/clothing/shoes/roman = 3,
		/obj/item/shield/roman/fake = 3,
		/obj/item/clothing/suit/chaplainsuit/clownpriest = 3,
		/obj/item/clothing/head/chaplain/clownmitre = 3,
		/obj/item/skub = 3,
		/obj/item/clothing/suit/hooded/mysticrobe = 3,
		/obj/item/clothing/under/dress/wedding_dress = 3,
		/obj/item/clothing/under/suit/tuxedo = 3,
		/obj/item/clothing/head/costume/weddingveil = 3,
		/obj/item/storage/belt/fannypack/cummerbund = 3,
		/obj/item/clothing/suit/costume/drfreeze_coat = 3,
		/obj/item/clothing/under/costume/drfreeze = 3,
		/obj/item/clothing/head/costume/drfreezehat = 3,
	)
	refill_canister = /obj/item/vending_refill/autodrobe
	default_price = PAYCHECK_CREW * 0.8 //Default of 40.
	extra_price = PAYCHECK_COMMAND
	payment_department = ACCOUNT_SRV
	light_mask = "theater-light-mask"
	allow_custom = TRUE

/obj/item/vending_refill/autodrobe
	machine_name = "AutoDrobe"
	icon_state = "refill_costume"
