GLOBAL_LIST_EMPTY(ipc_screen_list)
GLOBAL_LIST_EMPTY(reploid_antenna_list)
GLOBAL_LIST_INIT(reploid_limb_list, list(
	LIMBS_HUMAN,
	LIMBS_REPLOID,
	LIMBS_IPC,
))
GLOBAL_LIST_INIT(ipc_limb_list, list(
	LIMBS_IPC_BISH,
	LIMBS_IPC_BISH2,
	LIMBS_IPC_HEPH,
	LIMBS_IPC_HEPH2,
	LIMBS_IPC_SHELL,
	LIMBS_IPC_WARD,
	LIMBS_IPC_XION,
	LIMBS_IPC_XION2,
	LIMBS_IPC_ZENG,
	LIMBS_IPC_GREYSCALE,
	LIMBS_IPC_SYNTH,
))
