#define SPELLBOOK_CUSTOMIZATION_BOOLEAN "boolean"
#define SPELLBOOK_CUSTOMIZATION_ANY_INPUT "any_input"
#define SPELLBOOK_CUSTOMIZATION_SLIDER "slider"
#define SPELLBOOK_CUSTOMIZATION_NUMERIC_INPUT "number_input"
