
#define NO_MANA_POOL (1<<0)
#define MANA_POOL_FULL (1<<1)

#define MANA_POOL_TRANSFER_START (1<<2)
#define MANA_POOL_TRANSFER_STOP (1<<3)

#define MANA_POOL_ALREADY_TRANSFERRING (1<<4)
#define MANA_POOL_CANNOT_TRANSFER (1<<5)

#define MANA_POOL_TRANSFER_SKIP_ACTIVE (1<<6)
